apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: mar20-testnewgitops-codegen
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar20-testnewgitops-codegen
  name: mar20-testnewgitops-codegen
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: mar20-testnewgitops-codegen
    weight: 100
  wildcardPolicy: None
